"""create core content tables

Revision ID: 4be403c69ae5
Revises: 
Create Date: 2026-07-30 00:44:41.118628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be403c69ae5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('sheet_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_cards', sa.Integer(), server_default='0', nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('card_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('not_started', 'learning', 'learned', 'due', name='sheet_status', native_enum=False, create_constraint=True), server_default='not_started', nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='sheet_priority', native_enum=False, create_constraint=True), server_default='medium', nullable=False),
    sa.Column('first_learned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('srs_level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('interval_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lapse_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workbook_id', 'position', name='uq_study_sheets_workbook_position')
    )
    with op.batch_alter_table('study_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sheets_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('example_en', sa.Text(), nullable=True),
    sa.Column('example_vi', sa.Text(), nullable=True),
    sa.Column('is_weak', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_bookmarked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('correct_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('incorrect_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_result', sa.String(length=32), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['study_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_id', 'position', name='uq_flashcards_sheet_position')
    )
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcards_sheet_id'), ['sheet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcards_sheet_id'))

    op.drop_table('flashcards')
    with op.batch_alter_table('study_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sheets_workbook_id'))

    op.drop_table('study_sheets')
    op.drop_table('workbooks')
    # ### end Alembic commands ###
